apiVersion: v2
appVersion: "1.0"
description: A Helm chart for ebs topology service SG
name: eric-enmsg-ebs-topology
version: 1.0.19-1
dependencies:
  - condition: eric-enm-common-helmchart-library.enabled
    name: eric-enm-common-helmchart-library
    repository: https://arm.epk.ericsson.se/artifactory/proj-enm-helm/
    version: 1.55.0-5